### ISSUE TITLE
AdonisJS requires "@adonisjs/assembler" in deploy on heroku

### ISSUE THREAD

**Issue by kevinka999** [adonisjs/assembler#18]
I'm trying to deploy my API in AdonisJS 5.0 on heroku, but when heroku try to run my migrations using `node ace migration:run --force` I always get the error below
`Error: AdonisJS requires "@adonisjs/assembler" in order to run typescript source directly`

I really dont know how to fix it, already tried manually add the @adonisjs/assembler on "dependencies" in `package.json`.

## Versions
Adonis JS: 5
Core: 5.0.4-preview-rc-2
Assembler: 3.0.6
Node: 12.18.2
Npm: 6.14.5

## Sample Code 
My procfile
`release: ENV_SILENT=true node ace migration:run --force`

My entire error
`
Error: AdonisJS requires "@adonisjs/assembler" in order to run typescript source directly
    at Object.registerTsHook (/app/node_modules/@adonisjs/core/build/src/utils/index.js:30:19)
    at App.onFind (/app/node_modules/@adonisjs/core/build/src/Ignitor/Ace/App/index.js:138:21)
    at /app/node_modules/@adonisjs/core/build/src/Ignitor/Ace/App/index.js:191:60
    at Hooks.excute (/app/node_modules/@adonisjs/ace/build/src/Hooks/index.js:44:19)
    at Kernel.find (/app/node_modules/@adonisjs/ace/build/src/Kernel/index.js:151:30)
    at Kernel.exec (/app/node_modules/@adonisjs/ace/build/src/Kernel/index.js:313:34)
    at Kernel.handle (/app/node_modules/@adonisjs/ace/build/src/Kernel/index.js:302:21)
    at async App.handle (/app/node_modules/@adonisjs/core/build/src/Ignitor/Ace/App/index.js:307:13)
    at async Ace.handle (/app/node_modules/@adonisjs/core/build/src/Ignitor/Ace/index.js:33:9)
`

**Comment by thetutlage** [comment]
You should be running migrations from the build directory. `node build/ace` or simply cd into the `build` directory and consider as the root of the project in the production server

**Comment by kevinka999** [comment]
OMG! that work.
To automate I create a new **.sh** file called `release.sh` and add the code bellow
`cd build`
`ENV_SILENT=true node ace migration:run --force`

and in my **Procfile** I changed to
`release: sh ./release.sh`
