### ISSUE TITLE
Attempting to make a validator using ace results in an exception

### ISSUE THREAD

**Issue by benswinburne** [adonisjs/assembler#5]
Attempting to make a validator using ace results in an exception.

```
λ ~/Sites/adonis5/api node ace make:validator Creative
✖  fatal     Error: Error in template /Users/benswinburne/Sites/adonis5/api/node_modules/@adonisjs/assembler/build/templates/validator.txt:19
Unexpected token '*'
    at template (/Users/benswinburne/Sites/adonis5/api/node_modules/@adonisjs/ace/build/src/utils/template.js:43:15)
    at Object.templateFromFile (/Users/benswinburne/Sites/adonis5/api/node_modules/@adonisjs/ace/build/src/utils/template.js:53:12)
    at GeneratorFile.toJSON (/Users/benswinburne/Sites/adonis5/api/node_modules/@adonisjs/ace/build/src/Generator/File.js:115:30)
    at Generator.run (/Users/benswinburne/Sites/adonis5/api/node_modules/@adonisjs/ace/build/src/Generator/index.js:40:35)
    at MakeValidator.generate (/Users/benswinburne/Sites/adonis5/api/node_modules/@adonisjs/assembler/build/commands/Make/Base.js:71:30)
    at MakeValidator.handle (/Users/benswinburne/Sites/adonis5/api/node_modules/@adonisjs/assembler/build/commands/Make/Validator.js:51:9)
    at Kernel.runCommand (/Users/benswinburne/Sites/adonis5/api/node_modules/@adonisjs/ace/build/src/Kernel/index.js:239:26)
    at CoreCommands.handle (/Users/benswinburne/Sites/adonis5/api/node_modules/@adonisjs/core/build/src/Ignitor/Ace/CoreCommands.js:95:9)
    at Ace.handle (/Users/benswinburne/Sites/adonis5/api/node_modules/@adonisjs/core/build/src/Ignitor/Ace/index.js:117:17)
```

## Package version
```
"@adonisjs/assembler": "^1.3.8",
"@adonisjs/ace": "^6.9.2",
"@adonisjs/core": "^5.0.0-preview-rc-1.3",
"@adonisjs/fold": "^6.3.5",
"@adonisjs/lucid": "^8.0.2",
```

## Node.js and npm version
```
λ ~/Sites/adonis5/api node -v
v13.11.0
λ ~/Sites/adonis5/api yarn -v
1.22.4
```

## Sample Code (to reproduce the issue)
```
node ace make:validator Creative
```

**Comment by thetutlage** [comment]
Mind upgrading `@adonisjs/assembler` to `2.0.2`?

**Comment by benswinburne** [comment]
Works 👍 

Apologies I'd not notice how out of date my copy of assembler was. I've not really got used to the mental model of importing lots of different packages to make core functionality work (I know this isn't the case exactly here).

I vaguely recall seeing somewhere you plan to consolidate a lot of the separate packages' functionality into core so there's less compatibility creep possible from the different versions- presumably this will be the case with assembler?

**Comment by thetutlage** [comment]
assembler is a development dependency and cannot be merged inside core, otherwise you'll end up shipping unneccessary code and dependencies to production.

Otherwise a lot has been already merged to core

**Comment by thetutlage** [comment]
Closing, since not really an issue
